In [1]:
import os
import pandas as pd
import ast
from itertools import chain
from collections import Counter
import pickle
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from tqdm.notebook import tqdm
tqdm.pandas()

In [ ]:
db_file_path = '/mnt/share/kaichixie/A2H_preclinical_database/outputs/preclinical_db/v2/a2h_database_version_2.xlsx'
pcdb = pd.read_excel(db_file_path, engine="openpyxl", dtype=str,
                       sheet_name='A2H_database_version_2', keep_default_na=False)

unmapped_extractions = pd.read_excel(db_file_path,
                          sheet_name="unmapped_extractions", engine="openpyxl", dtype=str,
                          keep_default_na=False)

with open("/mnt/share/kaichixie/A2H_preclinical_database/data/mesh/mesh_synonyms_look_up_table.pkl", 'rb') as f:
    mesh_synonyms_LUT = pickle.load(f)
    
with open("/mnt/share/kaichixie/A2H_preclinical_database/data/drugbank/drugbank_synonyms_look_up_table.pkl", 'rb') as f:
    drugbank_synonyms_LUT = pickle.load(f)

with open("/mnt/share/kaichixie/A2H_preclinical_database/data/drugbank/drugbank_common_name_look_up_table.pkl", 'rb') as f:
    drugbank_common_name_LUT = pickle.load(f)

with open("/mnt/share/kaichixie/A2H_preclinical_database/data/UMLS/UMLS_synonyms_look_up_table.pkl", 'rb') as f:
    umls_synonyms_LUT = pickle.load(f)

pcdb["drug_external_ids"] = pcdb["drug_external_ids"].apply(lambda x: ast.literal_eval(x) if x != '' else x)

In [142]:
pcdb_drug = pcdb.explode("drug_external_ids")
pcdb_drug = pcdb_drug[pcdb_drug['drug_external_ids']!=""].copy()

In [143]:
pcdb_drug["drugbank_id"] = \
    pcdb_drug["drug_external_ids"].apply(lambda x : x['drugbank'] if ('drugbank' in x) else "")
pcdb_drug = pcdb_drug[pcdb_drug['drugbank_id']!='']

drugbank_ids = pcdb_drug['drugbank_id'].to_list()
drugbank_ids = list(chain.from_iterable(drugbank_ids))
drugbank_ids = list(set(drugbank_ids))

In [144]:
pcdb_drug_entities = \
    pd.DataFrame.from_dict({"drugbank_id": drugbank_ids})

drug_PCDB_ids = [f"PCDB_DR{i}" for i in range(1, len(pcdb_drug_entities)+1)]
pcdb_drug_entities["PCDB_id"] = drug_PCDB_ids

In [145]:
drugbank_ids_to_mesh_ids = {}
for db_id in pcdb_drug_entities['drugbank_id'].unique():
    drugbank_ids_to_mesh_ids[db_id] = set()

for d_eids in tqdm(pcdb["drug_external_ids"].to_list(), total=len(pcdb)):
    for d_eid in d_eids:
        if 'drugbank' in d_eid and 'mesh' in d_eid:
            db_ids = d_eid['drugbank']
            for db_id in db_ids:
                if db_id in drugbank_ids_to_mesh_ids:
                    for mesh_id in d_eid['mesh']:
                        drugbank_ids_to_mesh_ids[db_id].add(mesh_id)

  0%|          | 0/186627 [00:00<?, ?it/s]

In [146]:
pcdb_drug_entities["mesh_id"] = \
    pcdb_drug_entities["drugbank_id"].apply(lambda x: list(drugbank_ids_to_mesh_ids[x]) if len(drugbank_ids_to_mesh_ids[x]) != 0 else "")

In [147]:
mesh_ids_linked_drugbank = \
    list(chain.from_iterable(pcdb_drug_entities['mesh_id'].to_list()))
mesh_ids_linked_drugbank = set(mesh_ids_linked_drugbank)

In [148]:
pcdb_drug_MeSH = pcdb.explode("drug_external_ids")
pcdb_drug_MeSH = pcdb_drug_MeSH[pcdb_drug_MeSH['drug_external_ids']!=""]

pcdb_drug_MeSH["drug_mesh_id"] = \
    pcdb_drug_MeSH["drug_external_ids"].apply(lambda x : x['mesh'] if ('mesh' in x) else "")
pcdb_drug_MeSH = pcdb_drug_MeSH[pcdb_drug_MeSH['drug_mesh_id']!='']

pcdb_drug_MeSH = pcdb_drug_MeSH.explode("drug_mesh_id")
all_mapped_drug_mesh_ids = pcdb_drug_MeSH['drug_mesh_id'].unique().tolist()
mapped_drug_mesh_ids_not_linked_drugbank = \
    [x for x in all_mapped_drug_mesh_ids if x not in mesh_ids_linked_drugbank]

In [149]:
mesh_data = pd.read_csv('/mnt/share/kaichixie/A2H_preclinical_database/data/mesh/mesh_data.tsv',
                        sep='\t')
mesh_data = mesh_data.set_index("mesh_id")

In [150]:
def create_tree_id_lut():
    mesh_desc_data = \
        pd.read_csv("/mnt/share/kaichixie/A2H_preclinical_database/data/mesh/mesh_descriptive_data.tsv",
                    sep="\t")
    mesh_desc_data["tree_numbers"] = \
        mesh_desc_data["tree_numbers"].apply(lambda x: ast.literal_eval(x))
    tree_id_lut = {}
    
    for _, row in mesh_desc_data.iterrows():
        # print(row['mesh_id'])
        tree_id_lut[row['mesh_id']] = row['tree_numbers']
    return tree_id_lut

mesh_tree_id_lut = create_tree_id_lut()

In [151]:
drug_mesh_ids_with_PA = set()
for m_id in mapped_drug_mesh_ids_not_linked_drugbank:
    if m_id not in mesh_tree_id_lut:
        pas = mesh_data.loc[m_id]['pharmacological_actions']
        pas = ast.literal_eval(pas)
        if len(pas) > 0:
            drug_mesh_ids_with_PA.add(m_id)
    else:
        tree_ids = mesh_tree_id_lut[m_id]
        top_tree_id = set([x.split(".")[0] for x in tree_ids])
        # print(top_tree_id)
        for tid in top_tree_id:
            if tid.startswith('D'):
                drug_mesh_ids_with_PA.add(m_id)
                break

In [152]:
current_id_max = len(pcdb_drug_entities)
for mesh_id in drug_mesh_ids_with_PA:
    new_row = pd.DataFrame.from_dict({
        "drugbank_id" : "",
        "PCDB_id": f"PCDB_DR{current_id_max+1}",
        "mesh_id": [mesh_id]
    })
    current_id_max = current_id_max + 1
    pcdb_drug_entities = pd.concat([pcdb_drug_entities, new_row],
                                   ignore_index=True)

In [153]:
drugbank_id_to_UMLS_id = {}
for db_id in pcdb_drug_entities[pcdb_drug_entities['drugbank_id']!='']['drugbank_id'].unique():
    drugbank_id_to_UMLS_id[db_id] = set()

mesh_id_to_UMLS_id = {}
all_mesh_id = pcdb_drug_entities.explode('mesh_id')
for m_id in all_mesh_id[all_mesh_id['mesh_id']!='']['mesh_id'].unique():
    mesh_id_to_UMLS_id[m_id] = set()

In [154]:
for d_eids in tqdm(pcdb["drug_external_ids"].to_list(), total=len(pcdb)):
    for d_eid in d_eids: # each drug mapping
        if 'drugbank' in d_eid and 'UMLS' in d_eid:
            db_ids = d_eid['drugbank']
            for db_id in db_ids:
                if db_id in drugbank_id_to_UMLS_id:
                    for umls_id in d_eid['UMLS']:
                        drugbank_id_to_UMLS_id[db_id].add(umls_id)
        if 'mesh' in d_eid and 'UMLS' in d_eid:
            mesh_ids = d_eid['mesh']
            for mesh_id in mesh_ids:
                if mesh_id in mesh_id_to_UMLS_id:
                    for umls_id in d_eid['UMLS']:
                        mesh_id_to_UMLS_id[mesh_id].add(umls_id)

  0%|          | 0/186627 [00:00<?, ?it/s]

In [155]:
# Update drug entities df
pcdb_drug_entities["UMLS_id"] = \
    pcdb_drug_entities["drugbank_id"].apply(lambda x: drugbank_id_to_UMLS_id[x] if x != ''  else '')

In [156]:
def find_UMLS_id_by_mesh_id(row):
    mesh_ids = row["mesh_id"]
    if mesh_ids == '':
        return ""
    if isinstance(mesh_ids, str):
        mesh_ids = [mesh_ids]
        
    curr_umls_ids = row["UMLS_id"]
    if curr_umls_ids == '':
        curr_umls_ids = set()
    for mesh_id in mesh_ids:
        if mesh_id in mesh_id_to_UMLS_id:
            curr_umls_ids.update(mesh_id_to_UMLS_id[mesh_id])
    if len(curr_umls_ids) == 0:
        return ''
    return curr_umls_ids
            
pcdb_drug_entities["UMLS_id"] = pcdb_drug_entities.apply(find_UMLS_id_by_mesh_id, axis=1)

In [157]:
pcdb_drug_entities["UMLS_id"] = \
    pcdb_drug_entities["UMLS_id"].apply(lambda x: list(x) if x != '' else x)

In [158]:
resolved_UMLS_ids = pcdb_drug_entities[pcdb_drug_entities["UMLS_id"]!='']["UMLS_id"].to_list()
resolved_UMLS_ids = list(chain.from_iterable(resolved_UMLS_ids))
resolved_UMLS_ids = set(resolved_UMLS_ids)

In [ ]:
unresolved_UMLS_ids = set()
for d_eids in tqdm(pcdb["drug_external_ids"].to_list(), total=len(pcdb)):
    for d_eid in d_eids: # each drug mapping
        if 'UMLS' in d_eid: # Only mapped to UMLS
            for umls_id in d_eid['UMLS']:
                if umls_id not in resolved_UMLS_ids:
                    # print(umls_id, " resolved")
                    unresolved_UMLS_ids.add(umls_id)

In [160]:
with open('/mnt/share/kaichixie/A2H_preclinical_database/data/UMLS/UMLS_semantic_LUT.pkl', 'rb') as f:
    umls_semantic_lut = pickle.load(f)

In [161]:
allowed_semantic_types = ['T195', #Antibiotic,
                          'T200', # Clinical drugs
                          'T121'] # Pharmalogical substance
unresolved_drug_UMLS_ids = set()
for umls_id in unresolved_UMLS_ids:
    s_types = umls_semantic_lut[umls_id]
    for s_t in s_types:
        if s_t in allowed_semantic_types:
            unresolved_drug_UMLS_ids.add(umls_id)

In [162]:
# 
current_id_max = len(pcdb_drug_entities)
for new_umls_id in unresolved_drug_UMLS_ids:
    new_row = pd.DataFrame.from_dict({
        "drugbank_id" : "",
        "PCDB_id": f"PCDB_DR{current_id_max+1}",
        "mesh_id": "",
        "UMLS_id": [new_umls_id]
    })
    current_id_max = current_id_max + 1
    pcdb_drug_entities = pd.concat([pcdb_drug_entities, new_row],
                                   ignore_index=True)
pcdb_drug_entities

      drugbank_id       PCDB_id    mesh_id               UMLS_id
0         DB01119      PCDB_DR1  [D003981]            [C0012022]
1         DB12380      PCDB_DR2  [C579046]            [C2981796]
2         DB01620      PCDB_DR3  [D010632]  [C0031408, C0887016]
3         DB12064      PCDB_DR4  [C550356]            [C2346911]
4         DB00440      PCDB_DR5  [D014295]  [C0041041, C0801990]
...           ...           ...        ...                   ...
11748              PCDB_DR11749                         C1615056
11749              PCDB_DR11750                         C0876102
11750              PCDB_DR11751                         C0971163
11751              PCDB_DR11752                         C4053715
11752              PCDB_DR11753                         C1509016

[11753 rows x 4 columns]

In [187]:
# get drug name, and synonyms
def get_drug_synonyms(row):
    drugbank_id = row["drugbank_id"]
    mesh_id = row["mesh_id"]
    umls_id = row['UMLS_id']
    official_drug_name = ""
    official_synonyms = []
    if drugbank_id != "":
        official_drug_name = drugbank_common_name_LUT[drugbank_id]
    elif mesh_id != "":
        official_drug_name = mesh_synonyms_LUT[mesh_id][0]
    else:
        official_drug_name = f"UMLS_{umls_id}"
    
    if drugbank_id != "":
        official_synonyms = official_synonyms + drugbank_synonyms_LUT[drugbank_id]
    if mesh_id != "":
        if isinstance(mesh_id, str):
            mesh_id = [mesh_id]
        for m_id in mesh_id:
            official_synonyms = official_synonyms + mesh_synonyms_LUT[m_id]
    if umls_id != "":
        if isinstance(umls_id, str):
            umls_id = [umls_id]
        for u_id in umls_id:
            official_synonyms = official_synonyms + umls_synonyms_LUT[u_id]
    
    official_synonyms = [s.lower() for s in official_synonyms]
    official_synonyms = list(set(official_synonyms))
    return official_drug_name, official_synonyms

In [188]:
pcdb_drug_entities[["drug_name", "drug_synonyms"]] = \
    pcdb_drug_entities.apply(get_drug_synonyms, axis=1, result_type='expand')

In [195]:
def representative_name_for_cui(
    mrconso,
    cui,
    tty_priority=("PT", "PN", "MH", "HT", "SY"),
    sab_priority= None,
):

    # 1) filter rows for the CUI
    df = mrconso[mrconso["CUI"] == cui]
    # print(cui)
        

    # 3) scoring helpers (higher is better)
    tty_rank = {t: (len(tty_priority) - i) for i, t in enumerate(tty_priority)}
    sab_rank = {s: (len(sab_priority) - i) for i, s in enumerate(sab_priority)} if sab_priority else {}

    def score_row(r) -> tuple:
        # prefer ISPREF='Y', then TS='P', then TTY priority, then SAB priority,
        # then shorter string, then lexicographic stability
        ispref = 1 if str(r.get("ISPREF", "")).upper() == "Y" else 0
        ts_pref = 1 if str(r.get("TS", "")).upper() == "P" else 0
        tty = str(r.get("TTY", ""))
        sab = str(r.get("SAB", ""))
        strval = str(r.get("STR", ""))

        return (
            ispref,
            ts_pref,
            tty_rank.get(tty, 0),
            sab_rank.get(sab, 0),
            -len(strval),   # shorter is better
            strval.lower(), # stable tie-break
        )

    # 4) pick best row
    best = max(df.to_dict("records"), key=score_row)
    return best.get("STR")

In [191]:
mrconso_df = pd.read_csv('/mnt/share/kaichixie/A2H_preclinical_database/data/UMLS/2024AB/META/MRCONSO.RRF',
                         sep='|', header=None, dtype=str).iloc[:, :-1]
mrconso_df.columns = [
    'CUI', 'LAT', 'TS', 'LUI', 'STT', 'SUI', 'ISPREF', 'AUI', 'SAUI',
    'SCUI', 'SDUI', 'SAB', 'TTY', 'CODE', 'STR', 'SRL', 'SUPPRESS', 'CVF'
]

In [197]:
from pandarallel import pandarallel

pandarallel.initialize(progress_bar=True)

INFO: Pandarallel will run on 16 workers.
INFO: Pandarallel will use Memory file system to transfer data between the main process and workers.

In [198]:
pcdb_drug_entities['drug_name'] = \
    pcdb_drug_entities['drug_name'].parallel_apply(lambda x: representative_name_for_cui(mrconso_df, x[5:]) if x.startswith("UMLS") else x)

VBox(children=(HBox(children=(IntProgress(value=0, description='0.00%', max=735), Label(value='0 / 735'))), HB…

In [202]:
pcdb_drug_entities.columns

Index(['drugbank_id', 'PCDB_id', 'mesh_id', 'UMLS_id', 'drug_name',
       'drug_synonyms'],
      dtype='object')

In [203]:
pcdb_drug_entities = pcdb_drug_entities[[
    'PCDB_id', 'drug_name', 'drug_synonyms', 
    'drugbank_id', 'mesh_id', 'UMLS_id'
]]

In [204]:
pcdb_drug_entities.to_csv(os.path.join('/mnt/share/kaichixie/A2H_preclinical_database/outputs/preclinical_db/v3',
                                          "drug_entities.tsv"),
                                          sep='\t',
                                          index=False)

In [165]:
pcdb_id_lut_only_db_ids = {}
first_cover_drugbank = pcdb_drug_entities[pcdb_drug_entities['drugbank_id']!='']
for pcdb_id, db_id in zip(first_cover_drugbank["PCDB_id"].tolist(),
                            first_cover_drugbank["drugbank_id"].tolist()):
    pcdb_id_lut_only_db_ids[db_id] = pcdb_id

In [166]:
second_cover_mesh = \
    pcdb_drug_entities[pcdb_drug_entities['mesh_id'].apply(lambda x: (x!='') and (isinstance(x, str)))]
pcdb_id_lut_only_mesh_ids = {}
for pcdb_id, mesh_id in zip(second_cover_mesh["PCDB_id"].tolist(),
                            second_cover_mesh["mesh_id"].tolist()):
    pcdb_id_lut_only_mesh_ids[mesh_id] = pcdb_id

In [167]:
third_cover_umls = \
    pcdb_drug_entities[pcdb_drug_entities['UMLS_id'].apply(lambda x: (x!='') and (isinstance(x, str)))]
pcdb_id_lut_only_umls_ids = {}
for pcdb_id, umls_id in zip(third_cover_umls["PCDB_id"].tolist(),
                            third_cover_umls["UMLS_id"].tolist()):
    pcdb_id_lut_only_umls_ids[umls_id] = pcdb_id

In [177]:
def get_pcdb_id(row):
    d_eids = row["drug_external_ids"]
    drug_names = row["drug_names"]
    unresolved_drug_names = []
    unresolved_drug_external_ids = []
    pcdb_ids = []
    for drug_name, drug_eid in zip(drug_names, d_eids):
        resolved = False
        if 'drugbank' in drug_eid:
            for db_id in drug_eid["drugbank"]:
                pcdb_ids.append(pcdb_id_lut_only_db_ids[db_id])
                resolved = True
        elif 'mesh' in drug_eid:
            for mesh_id in drug_eid["mesh"]:
                if mesh_id in pcdb_id_lut_only_mesh_ids:
                    pcdb_ids.append(pcdb_id_lut_only_mesh_ids[mesh_id])
                    resolved = True
        elif 'UMLS' in drug_eid:
            for umls_id in drug_eid["UMLS"]:
                if umls_id in pcdb_id_lut_only_umls_ids:
                    pcdb_ids.append(pcdb_id_lut_only_umls_ids[umls_id])
                    resolved = True
        if not resolved:
            unresolved_drug_names.append(drug_name)
            unresolved_drug_external_ids.append(drug_eid)
            
    if len(pcdb_ids) == 0:
        pcdb_ids = ''
    if len(unresolved_drug_names) == 0:
        unresolved_drug_names = ''
        unresolved_drug_external_ids = ''

    return pcdb_ids, unresolved_drug_names, unresolved_drug_external_ids
        
pcdb[["drug_pcdb_ids", 'unresolved_drug_names', 'unresolved_drug_external_ids']] = pcdb.apply(lambda x: get_pcdb_id(x), result_type='expand', axis=1)

In [174]:
pcdb['drug_names'] = pcdb['drug_names'].apply(lambda x: ast.literal_eval(x) if x != '' else '')

In [169]:
pcdb[pcdb['drug_pcdb_ids'] != '']['pmcid'].nunique()

79796

In [178]:
pcdb.head(50)

,pmcid,date,link,confidence_score,TITLE,disease_names,disease_external_ids,drug_names,drug_external_ids,animal_strain,animal_species,total_subject_size,animal_external_ids,drug_pcdb_ids,unresolved_drug_names,unresolved_drug_external_ids
0,PMC10000236,2023-02-22,https://pmc.ncbi.nlm.nih.gov/articles/PMC10000236,0.9972,The Anti-Tumor Effect of the Newly Developed L...,['colorectal cancer'],"[{'mesh': ['D015179'], 'diseaseontology': ['DO...",[jph203],"[{'pubchem': ['CID:24853505'], 'mesh': ['C5481...",balb/c,mouse,,{'mesh': 'D051379'},,[jph203],"[{'pubchem': ['CID:24853505'], 'mesh': ['C5481..."
1,PMC10000284,2021-10-18,https://pmc.ncbi.nlm.nih.gov/articles/PMC10000284,0.9948,KDM1A inhibition augments the efficacy of rapa...,['endometrial cancer'],"[{'mesh': ['D016889'], 'diseaseontology': ['DO...","[ncd38, rapamycin, sp2509]","[{'pubchem': ['CID:127031303']}, {'pubchem': [...","athymic, nude",mouse,16,{'mesh': 'D051379'},[PCDB_DR1916],"[ncd38, sp2509]","[{'pubchem': ['CID:127031303']}, {'pubchem': [..."
2,PMC10000284,2021-10-18,https://pmc.ncbi.nlm.nih.gov/articles/PMC10000284,0.9948,KDM1A inhibition augments the efficacy of rapa...,['endometrial cancer'],"[{'mesh': ['D016889'], 'diseaseontology': ['DO...","[ncd38, rapamycin, sp2509]","[{'pubchem': ['CID:127031303']}, {'pubchem': [...",nsg,mouse,14-16,{'mesh': 'D051379'},[PCDB_DR1916],"[ncd38, sp2509]","[{'pubchem': ['CID:127031303']}, {'pubchem': [..."
3,PMC10000367,2023-03-02,https://pmc.ncbi.nlm.nih.gov/articles/PMC10000367,0.9399,"Micrandilactone C, a Nortriterpenoid Isolated ...","[""huntington's disease""]","[{'mesh': ['D006816'], 'diseaseontology': ['DO...",[methylcobalamin],"[{'pubchem': ['CID:10898559', 'CID:71306319', ...",c57bl/6,mouse,105,{'mesh': 'D051379'},[PCDB_DR4424],,
4,PMC10000396,2023-03-06,https://pmc.ncbi.nlm.nih.gov/articles/PMC10000396,0.9876,Sodium New Houttuyfonate Induces Apoptosis of ...,['breast cancer'],"[{'mesh': ['D001943'], 'diseaseontology': ['DO...","[sodium new houttuyfonate, docetaxel]","[{'pubchem': ['CID:44602651'], 'mesh': ['C5563...",balb/c,mouse,,{'mesh': 'D051379'},[PCDB_DR1180],[sodium new houttuyfonate],"[{'pubchem': ['CID:44602651'], 'mesh': ['C5563..."
5,PMC10000467,2023-03-03,https://pmc.ncbi.nlm.nih.gov/articles/PMC10000467,0.9325,Melatonin Inhibits VEGF-Induced Endothelial Pr...,['neovascular age-related macular degeneration'],"[{'diseaseontology': ['DOID:10873'], 'UMLS': [...","[bevacizumab, melatonin]","[{'drugbank': ['DB00112'], 'mesh': ['D00006825...",c57bl/6j,mouse,,{'mesh': 'D051379'},"[PCDB_DR167, PCDB_DR4371]",,
6,PMC10000467,2023-03-03,https://pmc.ncbi.nlm.nih.gov/articles/PMC10000467,0.9325,Melatonin Inhibits VEGF-Induced Endothelial Pr...,['neovascular age-related macular degeneration'],"[{'diseaseontology': ['DOID:10873'], 'UMLS': [...","[bevacizumab, melatonin]","[{'drugbank': ['DB00112'], 'mesh': ['D00006825...",,chicken,,{'mesh': 'D002645'},"[PCDB_DR167, PCDB_DR4371]",,
7,PMC10000472,2023-02-22,https://pmc.ncbi.nlm.nih.gov/articles/PMC10000472,0.9141,Sulforaphane Potentiates Gemcitabine-Mediated ...,['intrahepatic cholangiocarcinoma'],"[{'mesh': ['D018281'], 'diseaseontology': ['DO...","[sulforaphane, gemcitabine]","[{'pubchem': ['CID:5350'], 'drugbank': ['DB124...",balb/cslc-nu/nu,mouse,80,{'mesh': 'D051379'},"[PCDB_DR309, PCDB_DR3059]",,
8,PMC10000671,2023-03-04,https://pmc.ncbi.nlm.nih.gov/articles/PMC10000671,0.9903,Evaluation of Electrochemotherapy with Bleomyc...,"['hepatic cancer', 'colorectal hepatic metasta...","[{'mesh': ['D008113'], 'diseaseontology': ['DO...","[electrochemotherapy, bleomycin]","[{'mesh': ['D053672'], 'UMLS': ['C4721571']}, ...",wag/rij,rat,32,{'mesh': 'D051381'},[PCDB_DR2990],[electrochemotherapy],"[{'mesh': ['D053672'], 'UMLS': ['C4721571']}]"
9,PMC10000780,2023-02-23,https://pmc.ncbi.nlm.nih.gov/articles/PMC10000780,0.9770,Stem Cell Factor and Granulocyte Colony-Stimul...,['traumatic brain injury'],"[{'mesh': ['D000070642'], 'diseaseontology': [...","[stem cell factor, granulocyte colony-stimulat...","[{'mesh': ['D019089'], 'UMLS': ['C0143630', 'C...",c57bl/6j,mouse,43,{'mesh': 'D051379'},"[PCDB_DR4991, PCDB_DR5577]",,
10,PMC10000871,2023-02-27,https://pmc.ncbi.nlm.nih.gov/articles/PMC10000871,0.9149,Constitutive Expression of a Cytotoxic Antican...,"['colon cancer', 'breast cancer']","[{'mesh': ['D003110'], 'diseaseontology': ['DO...",,,balb/c,mouse,5,{'mesh': 'D051379'},,,
11,PMC10000927,2023-02-25,https://pmc.ncbi.nlm.nih.gov/articles/PMC10000927,0.9954,NSC243928 Treatment Induces Anti-Tumor Immune ...,['triple-negative breast cancer'],"[{'mesh': ['D064726'], 'UMLS': ['C4722518', 'C...",[nsc243928],"[{'pubchem': ['CID:151601'], 'mesh': ['C000726...",c57bl6,mouse,5,{'mesh': 'D051379'},,[nsc243928],"[{'pubchem': ['CID:151601'], 'mesh': ['C000726..."
12,PMC10000927,2023-02-25,https://pmc.ncbi.nlm.nih.gov/articles/PMC10000927,0.9954,NSC243928 Treatment Induces Anti-Tumor Immune ...,['triple-negative breast cancer'],"[{'mesh': ['D064726'], 'UMLS': ['C4722518', 'C...",[nsc243928],"[{'pubchem': ['CID:151601'], 'mesh': ['C000726...",balbc,mouse,10,{'mesh': 'D051379'},,[nsc243928],"[{'pubchem': ['CID:151601'], 'mesh': ['C000726..."
13,PMC10001016,2023-03-06,https://pmc.ncbi.nlm.nih.gov/articles/PMC10001016,0.9047,PKCθ Regulates Pituitary Adenoma Bone Invasion...,['pituitary adenoma bone invasion'],[{'mesh': ['D010911']}],"[sotrastaurin, celastrol]","[{'pubchem': ['CID:10296883'], 'drugbank': ['D...",balb/c athymic nude,mouse,,{'mesh': 'D051379'},"[PCDB_DR4225, PCDB_DR2059]",,
14,PMC10001020,2023-03-05,https://pmc.ncbi.nlm.nih.gov/articles/PMC10001020,0.9933,"A Novel Phenazine Analog, CPUL1, Suppresses Au...",['hepatocellular carcinoma'],"[{'mesh': ['D006528'], 'diseaseontology': ['DO...","[sorafenib, cpul1, cyclophosphamide]","[{'pubchem': ['CID:216239'], 'drugbank': ['DB0...",balb/c-nu-nu,mouse,36,{'mesh': 'D051379'},"[PCDB_DR3706, PCDB_DR1062]",[cpul1],[{'pubchem': ['CID:137645134']}]
15,PMC10001065,2023-02-23,https://pmc.ncbi.nlm.nih.gov/articles/PMC10001065,0.9922,Oligonucleotide Enhancing Compound Increases T...,['duchenne muscular dystrophy'],"[{'mesh': ['D020388'], 'diseaseontology': ['DO...",[unc7938],"[{'pubchem': ['CID:57402790'], 'mesh': ['C0006...",mdx,mouse,,{'mesh': 'D051379'},,[unc7938],"[{'pubchem': ['CID:57402790'], 'mesh': ['C0006..."
16,PMC10001065,2023-02-23,https://pmc.ncbi.nlm.nih.gov/articles/PMC10001065,0.9922,Oligonucleotide Enhancing Compound Increases T...,['duchenne muscular dystrophy'],"[{'mesh': ['D020388'], 'diseaseontology': ['DO...",[unc7938],"[{'pubchem': ['CID:57402790'], 'mesh': ['C0006...",c57bl/10,mouse,,{'mesh': 'D051379'},,[unc7938],"[{'pubchem': ['CID:57402790'], 'mesh': ['C0006..."
17,PMC10001131,2023-02-28,https://pmc.ncbi.nlm.nih.gov/articles/PMC10001131,0.9890,Periplocin Overcomes Bortezomib Resistance by ...,['multiple myeloma'],"[{'mesh': ['D009101'], 'diseaseontology': ['DO...",[periplocin],"[{'pubchem': ['CID:14463159'], 'mesh': ['C5023...",ncg,mouse,,{'mesh': 'D051379'},,[periplocin],"[{'pubchem': ['CID:14463159'], 'mesh': ['C5023..."
18,PMC10001142,2023-03-02,https://pmc.ncbi.nlm.nih.gov/articles/PMC10001142,0.9797,5-Fluorouracil Suppresses Colon Tumor through ...,['colorectal cancer'],"[{'mesh': ['D015179'], 'diseaseontology': ['DO...",[5-fu],"[{'pubchem': ['CID:3385'], 'drugbank': ['DB005...",balb/c,mouse,,{'mesh': 'D051379'},[PCDB_DR1534],,
19,PMC10001201,2023-03-03,https://pmc.ncbi.nlm.nih.gov/articles/PMC10001201,0.9770,Discovering Synergistic Compounds with BYL-719...,['basal-like triple-negative breast cancer'],[{'mesh': ['D064726']}],"[byl-719, afatinib, dronedarone, everolimus]","[{'pubchem': ['CID:56649450']}, {'pubchem': ['...",nsg,mouse,,{'mesh': 'D051379'},"[PCDB_DR2016, PCDB_DR4208, PCDB_DR2507]",[byl-719],[{'pubchem': ['CID:56649450']}]
20,PMC10001369,2023-03-03,https://pmc.ncbi.nlm.nih.gov/articles/PMC10001369,0.9961,ImmunoPET Imaging Identifies the Optimal Timep...,['triple-negative breast cancer'],"[{'mesh': ['D064726'], 'UMLS': ['C4722518', 'C...","[cdx-011, dasatinib]","[{'mesh': ['C551271'], 'UMLS': ['C2935737']}, ...",athymic nude,mouse,30,{'mesh': 'D051379'},[PCDB_DR3123],[cdx-011],"[{'mesh': ['C551271'], 'UMLS': ['C2935737']}]"
21,PMC10001413,2023-02-27,https://pmc.ncbi.nlm.nih.gov/articles/PMC10001413,0.9924,The Neuroprotective Activities of the Novel Mu...,"[""parkinson's disease"", ""alzheimer's disease"",...","[{'mesh': ['D010300'], 'diseaseontology': ['DO...",,,app/ps1,mouse,9,{'mesh': 'D051379'},,,
22,PMC10001413,2023-02-27,https://pmc.ncbi.nlm.nih.gov/articles/PMC10001413,0.9924,The Neuroprotective Activities of the Novel Mu...,"[""parkinson's disease"", ""alzheimer's disease"",...","[{'mesh': ['D010300'], 'diseaseontology': ['DO...",,,g93a-sod1,mouse,14-16,{'mesh': 'D051379'},,,
23,PMC10001413,2023-02-27,https://pmc.ncbi.nlm.nih.gov/articles/PMC10001413,0.9924,The Neuroprotective Activities of the Novel Mu...,"[""parkinson's disease"", ""alzheimer's disease"",...","[{'mesh': ['D010300'], 'diseaseontology': ['DO...",,,c57bl/6,mouse,12-11,{'mesh': 'D051379'},,,
24,PMC10001455,2023-02-21,https://pmc.ncbi.nlm.nih.gov/articles/PMC10001455,0.9933,Topical Diacerein Decreases Skin and Splenic C...,['psoriasis'],"[{'mesh': ['D011565'], 'diseaseontology': ['DO...","[placebo, diacerein]","[{'UMLS': ['C1696465', 'C0032042']}, {'pubchem...",c57bl/6ncrl,mouse,,{'mesh': 'D051379'},[PCDB_DR2824],[placebo],"[{'UMLS': ['C1696465', 'C0032042']}]"
25,PMC10001971,2023-02-23,https://pmc.ncbi.nlm.nih.gov/articles/PMC10001971,0.9325,Virus-like Particles of Nodavirus Displaying t...,['coronavirus disease 2019'],"[{'mesh': ['D000086382'], 'UMLS': ['C5203670']}]",,,balb/c,mouse,72,{'mesh': 'D051379'},,,
26,PMC10001983,2023-02-21,https://pmc.ncbi.nlm.nih.gov/articles/PMC10001983,0.9890,The Novel RXR Agonist MSU-42011 Differentially...,['breast cancer'],"[{'mesh': ['D001943'], 'diseaseontology': ['DO...","[bexarotene, msu-42011]","[{'pubchem': ['CID:82146'], 'drugbank': ['DB00...",c57bl/6,mouse,,{'mesh': 'D051379'},[PCDB_DR287],[msu-42011],[{'pubchem': ['CID:154656181']}]
27,PMC10001983,2023-02-21,https://pmc.ncbi.nlm.nih.gov/articles/PMC10001983,0.9890,The Novel RXR Agonist MSU-42011 Differentially...,['breast cancer'],"[{'mesh': ['D001943'], 'diseaseontology': ['DO...","[bexarotene, msu-42011]","[{'pubchem': ['CID:82146'], 'drugbank': ['DB00...",mmtv-neu,mouse,,{'mesh': 'D051379'},[PCDB_DR287],[msu-42011],[{'pubchem': ['CID:154656181']}]
28,PMC10002107,2023-02-22,https://pmc.ncbi.nlm.nih.gov/articles/PMC10002107,0.9820,Purification of PaTx-II from the Venom of the ...,['infections caused by multi-drug-resistant ba...,[{'mesh': ['D024901']}],,,balb/c,mouse,20,{'mesh': 'D051379'},,,
29,PMC10002165,2023-02-22,https://pmc.ncbi.nlm.nih.gov/articles/PMC10002165,0.9876,A Postsynaptic Density Immediate Early Gene-Ba...,['schizophrenia'],"[{'mesh': ['D012559'], 'diseaseontology': ['DO...",[aripiprazole],"[{'pubchem': ['CID:60795'], 'drugbank': ['DB01...",sprague-dawley,rat,20,{'mesh': 'D051381'},[PCDB_DR23],,
30,PMC10002220,2023-02-22,https://pmc.ncbi.nlm.nih.gov/articles/PMC10002220,0.9859,In Vivo Reversal of P-Glycoprotein-Mediated Dr...,"['breast cancer', 'leukemia']","[{'mesh': ['D001943'], 'diseaseontology': ['DO...","[paclitaxel, doxorubicin, c25]","[{'pubchem': ['CID:36314'], 'drugbank': ['DB01...",balb/c,mouse,25,{'mesh': 'D051379'},"[PCDB_DR1965, PCDB_DR3057]",[c25],"[{'pubchem': ['CID:6131'], 'UMLS': ['C1538701']}]"
31,PMC10002220,2023-02-22,https://pmc.ncbi.nlm.nih.gov/articles/PMC10002220,0.9859,In Vivo Reversal of P-Glycoprotein-Mediated Dr...,"['breast cancer', 'leukemia']","[{'mesh': ['D001943'], 'diseaseontology': ['DO...","[paclitaxel, doxorubicin, c25]","[{'pubchem': ['CID:36314'], 'drugbank': ['DB01...",balb/c nude,mouse,32,{'mesh': 'D051379'},"[PCDB_DR1965, PCDB_DR3057]",[c25],"[{'pubchem': ['CID:6131'], 'UMLS': ['C1538701']}]"
32,PMC10002220,2023-02-22,https://pmc.ncbi.nlm.nih.gov/articles/PMC10002220,0.9859,In Vivo Reversal of P-Glycoprotein-Mediated Dr...,"['breast cancer', 'leukemia']","[{'mesh': ['D001943'], 'diseaseontology': ['DO...","[paclitaxel, doxorubicin, c25]","[{'pubchem': ['CID:36314'], 'drugbank': ['DB01...",b6d2f1,mouse,3,{'mesh': 'D051379'},"[PCDB_DR1965, PCDB_DR3057]",[c25],"[{'pubchem': ['CID:6131'], 'UMLS': ['C1538701']}]"
33,PMC10002220,2023-02-22,https://pmc.ncbi.nlm.nih.gov/articles/PMC10002220,0.9859,In Vivo Reversal of P-Glycoprotein-Mediated Dr...,"['breast cancer', 'leukemia']","[{'mesh': ['D001943'], 'diseaseontology': ['DO...","[paclitaxel, doxorubicin, c25]","[{'pubchem': ['CID:36314'], 'drugbank': ['DB01...",nod/scid,mouse,3,{'mesh': 'D051379'},"[PCDB_DR1965, PCDB_DR3057]",[c25],"[{'pubchem': ['CID:6131'], 'UMLS': ['C1538701']}]"
34,PMC10002367,2023-02-21,https://pmc.ncbi.nlm.nih.gov/articles/PMC10002367,0.9933,"Evaluation of Anticancer Activity of Zhubech, ...",['pancreatic cancer'],"[{'mesh': ['D010190'], 'diseaseontology': ['DO...",[5-fu],"[{'pubchem': ['CID:3385'], 'drugbank': ['DB005...",nude,mouse,18,{'mesh': 'D051379'},[PCDB_DR1534],,
35,PMC10002367,2023-02-21,https://pmc.ncbi.nlm.nih.gov/articles/PMC10002367,0.9933,"Evaluation of Anticancer Activity of Zhubech, ...",['pancreatic cancer'],"[{'mesh': ['D010190'], 'diseaseontology': ['DO...",[5-fu],"[{'pubchem': ['CID:3385'], 'drugbank': ['DB005...",,mouse,15,{'mesh': 'D051379'},[PCDB_DR1534],,
36,PMC10002481,2023-03-02,https://pmc.ncbi.nlm.nih.gov/articles/PMC10002481,0.9941,PPAR Pan Agonist MHY2013 Alleviates Renal Fibr...,['chronic kidney diseases'],"[{'mesh': ['D051436'], 'UMLS': ['C1561643']}]",,,c57bl/6j,mouse,5-7,{'mesh': 'D051379'},,,
37,PMC10002482,2023-03-03,https://pmc.ncbi.nlm.nih.gov/articles/PMC10002482,0.9241,BMPER Improves Vascular Remodeling and the Con...,['occlusive cardiovascular diseases'],[{'mesh': ['D014652']}],,,b6sjl-bmpertm1emdr/j,mouse,,{'mesh': 'D051379'},,,
38,PMC10002482,2023-03-03,https://pmc.ncbi.nlm.nih.gov/articles/PMC10002482,0.9241,BMPER Improves Vascular Remodeling and the Con...,['occlusive cardiovascular diseases'],[{'mesh': ['D014652']}],,,c57/bl6n,mouse,,{'mesh': 'D051379'},,,
39,PMC10002513,2023-08-02,https://pmc.ncbi.nlm.nih.gov/articles/PMC10002513,0.9948,Resolvin E1 improves efferocytosis and rescues...,['severe aplastic anemia'],[{'UMLS': ['C1883018']}],[resolvin e1],"[{'pubchem': ['CID:10473088'], 'drugbank': ['D...",c57bl/6,mouse,,{'mesh': 'D051379'},[PCDB_DR505],,
40,PMC10002513,2023-08-02,https://pmc.ncbi.nlm.nih.gov/articles/PMC10002513,0.9948,Resolvin E1 improves efferocytosis and rescues...,['severe aplastic anemia'],[{'UMLS': ['C1883018']}],[resolvin e1],"[{'pubchem': ['CID:10473088'], 'drugbank': ['D...",balb/cann,mouse,,{'mesh': 'D051379'},[PCDB_DR505],,
41,PMC10002513,2023-08-02,https://pmc.ncbi.nlm.nih.gov/articles/PMC10002513,0.9948,Resolvin E1 improves efferocytosis and rescues...,['severe aplastic anemia'],[{'UMLS': ['C1883018']}],[resolvin e1],"[{'pubchem': ['CID:10473088'], 'drugbank': ['D...",miig,mouse,,{'mesh': 'D051379'},[PCDB_DR505],,
42,PMC10002513,2023-08-02,https://pmc.ncbi.nlm.nih.gov/articles/PMC10002513,0.9948,Resolvin E1 improves efferocytosis and rescues...,['severe aplastic anemia'],[{'UMLS': ['C1883018']}],[resolvin e1],"[{'pubchem': ['CID:10473088'], 'drugbank': ['D...",hybrid b6 f1,mouse,,{'mesh': 'D051379'},[PCDB_DR505],,
43,PMC10002537,2023-02-27,https://pmc.ncbi.nlm.nih.gov/articles/PMC10002537,0.9964,Loss of Extrasynaptic Inhibitory Glycine Recep...,"[""alzheimer's disease""]","[{'mesh': ['D000544'], 'diseaseontology': ['DO...",[artesunate],"[{'pubchem': ['CID:6917864', 'CID:65664', 'CID...",app/ps1,mouse,4-6,{'mesh': 'D051379'},[PCDB_DR4399],,
44,PMC10002537,2023-02-27,https://pmc.ncbi.nlm.nih.gov/articles/PMC10002537,0.9964,Loss of Extrasynaptic Inhibitory Glycine Recep...,"[""alzheimer's disease""]","[{'mesh': ['D000544'], 'diseaseontology': ['DO...",[artesunate],"[{'pubchem': ['CID:6917864', 'CID:65664', 'CID...",c57bl/6,mouse,,{'mesh': 'D051379'},[PCDB_DR4399],,
45,PMC10002561,2023-03-04,https://pmc.ncbi.nlm.nih.gov/articles/PMC10002561,0.9770,Therapeutic Effects of Cornuside on Particulat...,['pm2.5-induced lung injury'],[{'mesh': ['D055370']}],"[dexamethasone, cnidium officinale]","[{'pubchem': ['CID:5743'], 'drugbank': ['DB012...",balb/c,mouse,80,{'mesh': 'D051379'},[PCDB_DR4108],[cnidium officinale],[{'UMLS': ['C1018214']}]
46,PMC10002576,2023-03-03,https://pmc.ncbi.nlm.nih.gov/articles/PMC10002576,0.9707,The CaSR Modulator NPS-2143 Reduced UV-Induced...,['skin cancer'],"[{'mesh': ['D012878'], 'diseaseontology': ['DO...",[nps-2143],"[{'pubchem': ['CID:6918446'], 'drugbank': ['DB...",skh:hr1,mouse,18,{'mesh': 'D051379'},[PCDB_DR2068],,
47,PMC10002675,2023-02-23,https://pmc.ncbi.nlm.nih.gov/articles/PMC10002675,0.9627,"Revisiting Cryptocyanine Dye, NK-4, as an Old ...",,,,,royal college of surgeons,rat,,{'mesh': 'D051381'},,,
48,PMC10002675,2023-02-23,https://pmc.ncbi.nlm.nih.gov/articles/PMC10002675,0.9627,"Revisiting Cryptocyanine Dye, NK-4, as an Old ...",,,,,,golden syrian hamster,,{'mesh': 'D008647'},,,
49,PMC10002675,2023-02-23,https://pmc.ncbi.nlm.nih.gov/articles/PMC10002675,0.9627,"Revisiting Cryptocyanine Dye, NK-4, as an Old ...",,,,,tg 2576,mouse,,{'mesh': 'D051379'},,,

In [107]:
pcdb[pcdb['drug_external_ids'] != '']['pmcid'].nunique()

104381

In [110]:
79796 / 104381

0.764468629348253

In [ ]:
# get descriptor name, syonyms (all DB, MeSH, UMLS only allowed categories)

In [ ]:
# umls_only_ids = \
#     pcdb_drug_entities[(pcdb_drug_entities['drugbank_id'] == '') & (pcdb_drug_entities['mesh_id'] == '')]['UMLS_id'].to_list()
# prop_umls_ids = \
#     pcdb_drug_entities[(pcdb_drug_entities['drugbank_id'] != '') | (pcdb_drug_entities['mesh_id'] != '')]['UMLS_id'].to_list()
# prop_umls_ids = list(chain.from_iterable(prop_umls_ids))

# for k in umls_only_ids:
#     if k in prop_umls_ids:
#         print(k)